name: .NET NuGet Package CI (with optional DevExpress projects)

# Этот workflow собирает и публикует NuGet пакеты для всех проектов
# CommonForms будет включен только при успешном restore всех DevExpress зависимостей

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*' ]
  workflow_dispatch:

env:
  SOLUTION_PATH: CommonUtils/CommonUtils.sln
  TEMP_SOLUTION_PATH: CommonUtils/temp-ci.sln
  GITHUB_PACKAGES_URL: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json

jobs:
  build-and-pack:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Clean NuGet configuration
      run: |
        # Очищаем любые локальные конфиги с credentials чтобы избежать конфликтов
        if (Test-Path "nuget.config.user") {
          Remove-Item "nuget.config.user" -Force
          Write-Host "Removed local nuget.config.user file"
        }
        # Очищаем глобальные конфигурации NuGet
        dotnet nuget locals all --clear

    - name: Configure NuGet sources
      run: |
        # Удаляем существующие источники GitHub Packages
        dotnet nuget remove source "github" 2>$null || true
        dotnet nuget remove source "github-packages" 2>$null || true
        dotnet nuget remove source "local-packages" 2>$null || true

        # Добавляем источник для локальных DevExpress пакетов
        $localPackagesPath = "$(Get-Location)\LocalPackages"
        Write-Host "Adding local packages source: $localPackagesPath"
        dotnet nuget add source $localPackagesPath -n "local-packages"

        # Добавляем источник GitHub Packages с аутентификацией
        Write-Host "Adding GitHub Packages source: ${{ env.GITHUB_PACKAGES_URL }}"
        dotnet nuget add source "${{ env.GITHUB_PACKAGES_URL }}" -n "github-packages" -u "${{ github.actor }}" -p "${{ secrets.GITHUB_TOKEN }}" --store-password-in-clear-text

        # Проверка добавленных источников
        Write-Host "Configured NuGet sources:"
        dotnet nuget list source

    - name: Test DevExpress dependencies and prepare build
      run: |
        Write-Host "Проверяем возможность сборки CommonForms в CI"

        # Для CI/CD просто исключаем CommonForms чтобы избежать проблем с DevExpress
        Write-Host "❌ Исключаем CommonForms из CI/CD сборки (требует DevExpress)"
        "INCLUDE_COMMONFORMS=false" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
        "TARGET_SOLUTION=${{ env.SOLUTION_PATH }}" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8

    - name: Restore dependencies
      run: |
        Write-Host "Восстанавливаем зависимости для проектов (без CommonForms)"
        dotnet restore "$env:TARGET_SOLUTION"

    - name: Build
      run: |
        dotnet build "$env:TARGET_SOLUTION" --configuration Release --no-restore

    - name: Test
      run: |
        dotnet test "$env:TARGET_SOLUTION" --configuration Release --no-build --verbosity normal

    - name: Set Package Version
      run: |
        if ("${{ github.ref }}" -match '^refs/tags/v(.+)$') {
          $version = $matches[1]
          "PACKAGE_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
          Write-Host "Building release version: $version"
        } else {
          $version = "1.0.0-ci-${{ github.run_number }}"
          "PACKAGE_VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
          Write-Host "Building CI version: $version"
        }

    - name: Pack NuGet packages
      run: |
        if ($env:INCLUDE_COMMONFORMS -eq "true") {
          Write-Host "Пакуем все проекты (включая CommonForms)"
          $projects = Get-ChildItem -Recurse -Filter *.csproj | Where-Object {
            $_.FullName -notmatch 'test|Test'
          }
        } else {
          Write-Host "Пакуем проекты без CommonForms"
          $projects = Get-ChildItem -Recurse -Filter *.csproj | Where-Object {
            $_.FullName -notmatch 'test|Test|CommonForms'
          }
        }
        foreach ($project in $projects) {
          Write-Host "Packing $($project.Name) with version $env:PACKAGE_VERSION"
          dotnet pack $project.FullName --configuration Release -p:PackageVersion=$env:PACKAGE_VERSION --output nupkg
        }

    - name: List files in nupkg directory
      run: ls  nupkg/

    - name: Verify packages were created
      run: |
        if (!(Test-Path nupkg/*.nupkg)) {
          Write-Error "No nupkg files found!"
          exit 1
        }

        # Проверяем, что URL доступен
        Write-Host "GitHub Packages URL: ${{ env.GITHUB_PACKAGES_URL }}"
        Write-Host "GitHub Actor: ${{ github.actor }}"

        # Проверяем настройки NuGet
        dotnet nuget list source


    - name: Publish to GitHub Packages
      run: |
        $packages = Get-ChildItem -Path nupkg -Filter *.nupkg
        foreach ($package in $packages) {
          Write-Host "Publishing $($package.Name)"
          dotnet nuget push $package.FullName --source "${{ env.GITHUB_PACKAGES_URL }}" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
        }

    - name: Cleanup
      if: always()
      run: |
        # Удаляем временные файлы если они были созданы
        if (Test-Path "${{ env.TEMP_SOLUTION_PATH }}") {
          Remove-Item "${{ env.TEMP_SOLUTION_PATH }}" -Force
          Write-Host "Удален временный solution файл"
        }
